[pytest]
testpaths=tests
python_files=test_*.py
python_classes=Test*
python_functions=test_*

markers =
    smoke: quick critical API tests
    regression: full API regression tests
    api: API automation test
    negative: negative validation tests

addopts = -v --tb=short


